/*
 * gen-embedded-lut.ts - bake a real theme grade LUT with the TS engine and emit it
 * as a compiled-in C++ header (native/ColorGradeFX/embedded/EmbeddedLut.h).
 *
 * Why embed one: Phase 1's effect must always have a valid baked LUT to apply so it
 * is demonstrable with no external file, and so it genuinely exercises the ported
 * sampleLut on real IP output (a teal-orange grade), not a toy LUT. Users can still
 * override it with their own .cube via the effect's file param; this is the fallback.
 *
 * Emitted as a flat float array (not .cube text) on purpose: MSVC caps a single
 * string literal at 65,535 bytes, and a 33^3 cube is ~1 MB of text. An array has no
 * such limit. Kept at 17^3 so the header stays small and compiles fast - the default
 * is a demo fallback; user-supplied .cube files drive the full 33^3/65^3 path.
 *
 * Regenerate: npm run native:gen-lut  (re-run whenever the theme/engine changes).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bakeGradeLut } from '../../src/core/lut/gradeLut.js';
import { THEMES } from '../../src/themes/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'ColorGradeFX', 'embedded', 'EmbeddedLut.h');

// Stand-in footage: warm-film target stats graded toward the teal-orange theme.
// Produces a visibly non-identity teal-orange look (cool shadows, warm skin).
const theme = THEMES['teal-orange']!;
const stats = THEMES['warm-film']!.targetStats;
const size = 17;
const lut = bakeGradeLut(stats, theme, {}, size);

// Format the interleaved RGB data as C++ float initializers, wrapped for readability.
const values: string[] = [];
for (let i = 0; i < lut.data.length; i++) {
  values.push(`${lut.data[i]!.toFixed(6)}f`);
}
const perLine = 12;
const lines: string[] = [];
for (let i = 0; i < values.length; i += perLine) {
  lines.push('    ' + values.slice(i, i + perLine).join(', ') + ',');
}

const header = `/*
 * EmbeddedLut.h - GENERATED by native/scripts/gen-embedded-lut.ts. Do not edit by hand.
 *
 * A baked LUT (theme "${theme.name}" grade, ${size}^3) compiled into the plugin as the
 * default/fallback LUT. Interleaved RGB, red fastest - same ordering as .cube and as
 * cg::Lut3D::data. Regenerate with: npm run native:gen-lut
 */
#pragma once

#include "../lut/CubeLut.h"

namespace cg {

inline constexpr int kEmbeddedLutSize = ${size};

// ${lut.data.length} floats = ${size}^3 nodes * 3 channels.
inline const float kEmbeddedLutData[] = {
${lines.join('\n')}
};

// Build a Lut3D view over the embedded data (copies into the vector).
inline Lut3D EmbeddedLut() {
    Lut3D lut;
    lut.size = kEmbeddedLutSize;
    lut.data.assign(kEmbeddedLutData, kEmbeddedLutData + (sizeof(kEmbeddedLutData) / sizeof(float)));
    lut.title = "${theme.name} grade (embedded)";
    return lut;
}

}  // namespace cg
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header, 'utf8');
console.log(`Wrote ${outPath} (${theme.name} grade, ${size}^3, ${lut.data.length} floats)`);
